# Generated by Django 5.0.6 on 2024-05-16 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='course',
        ),
        migrations.AddField(
            model_name='module',
            name='course_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
