from datetime import datetime
from applications.models import DataProcessor  # replace 'myapp' with the actual app name

entityData = [
  {
    "id": 1,
    "entityName": "Intouch Communications",
    "registrationNumber": None,
    "licenseNumber": None,
    "lawNumber": None,
    "presidentialOrderNumber": None,
    "natureOfEntity": "Private",
    "entitySector": "IT",
    "entityAddress": "Kigali",
    "phoneNumber": "Intouch Communications",
    "emailAddress": "company@gmail.com",
    "website": None,
    "dpoName": "Rosine",
    "dpoPhoneNumber": "0785348283",
    "dpoEmailAddress": "benitha@gmail.com",
    "representativeName": None,
    "representativePhoneNumber": None,
    "representativeAddress": None,
    "representativeEmail": None,
    "representativeWebsite": None,
    "categoryOfDataSubjects": "Kigali",
    "purposeOfDataProcessing": "Intouch Communications",
    "transferOfPersonalDataOutsideRwanda": True,
    "transferCountry": None,
    "categoriesOfPersonalData": "IT",
    "sensitivePersonalData": True,
    "additionalInformation": None,
    "declarationName": "Tel Company",
    "declarationDesignation": "IT",
    "declarationDate": "2024-02-05"
  },
  {
    "id": 2,
    "entityName": "Tech Innovations",
    "registrationNumber": "123456",
    "licenseNumber": "LIC123456",
    "lawNumber": "LAW123",
    "presidentialOrderNumber": "PO123",
    "natureOfEntity": "Public",
    "entitySector": "Technology",
    "entityAddress": "Kigali",
    "phoneNumber": "Tech Innovations",
    "emailAddress": "techinnovations@gmail.com",
    "website": "www.techinnovations.com",
    "dpoName": "John Doe",
    "dpoPhoneNumber": "0785123456",
    "dpoEmailAddress": "johndoe@gmail.com",
    "representativeName": "Jane Smith",
    "representativePhoneNumber": "0785234567",
    "representativeAddress": "123 Tech Street",
    "representativeEmail": "janesmith@gmail.com",
    "representativeWebsite": "www.janesmith.com",
    "categoryOfDataSubjects": "Tech Enthusiasts",
    "purposeOfDataProcessing": "Data Analysis",
    "transferOfPersonalDataOutsideRwanda": False,
    "transferCountry": None,
    "categoriesOfPersonalData": "User Data",
    "sensitivePersonalData": False,
    "additionalInformation": "None",
    "declarationName": "Tech Innovations",
    "declarationDesignation": "CEO",
    "declarationDate": "2024-03-01"
  },
  {
    "id": 3,
    "entityName": "Health Services Ltd.",
    "registrationNumber": "654321",
    "licenseNumber": "LIC654321",
    "lawNumber": "LAW654",
    "presidentialOrderNumber": "PO654",
    "natureOfEntity": "Private",
    "entitySector": "Healthcare",
    "entityAddress": "Kigali",
    "phoneNumber": "Health Services Ltd.",
    "emailAddress": "healthservices@gmail.com",
    "website": "www.healthservices.com",
    "dpoName": "Alice Johnson",
    "dpoPhoneNumber": "0785345678",
    "dpoEmailAddress": "alicejohnson@gmail.com",
    "representativeName": "Bob Brown",
    "representativePhoneNumber": "0785456789",
    "representativeAddress": "456 Health Avenue",
    "representativeEmail": "bobbrown@gmail.com",
    "representativeWebsite": "www.bobbrown.com",
    "categoryOfDataSubjects": "Patients",
    "purposeOfDataProcessing": "Medical Records",
    "transferOfPersonalDataOutsideRwanda": True,
    "transferCountry": "Kenya",
    "categoriesOfPersonalData": "Health Data",
    "sensitivePersonalData": True,
    "additionalInformation": "Confidential",
    "declarationName": "Health Services Ltd.",
    "declarationDesignation": "CFO",
    "declarationDate": "2024-03-15"
  },
  {
    "id": 4,
    "entityName": "EduCare Foundation",
    "registrationNumber": "789123",
    "licenseNumber": "LIC789123",
    "lawNumber": "LAW789",
    "presidentialOrderNumber": "PO789",
    "natureOfEntity": "Non-Profit",
    "entitySector": "Education",
    "entityAddress": "Kigali",
    "phoneNumber": "EduCare Foundation",
    "emailAddress": "educarefoundation@gmail.com",
    "website": "www.educarefoundation.com",
    "dpoName": "Michael Green",
    "dpoPhoneNumber": "0785567890",
    "dpoEmailAddress": "michaelgreen@gmail.com",
    "representativeName": "Laura White",
    "representativePhoneNumber": "0785678901",
    "representativeAddress": "789 Education Road",
    "representativeEmail": "laurawhite@gmail.com",
    "representativeWebsite": "www.laurawhite.com",
    "categoryOfDataSubjects": "Students",
    "purposeOfDataProcessing": "Academic Records",
    "transferOfPersonalDataOutsideRwanda": False,
    "transferCountry": None,
    "categoriesOfPersonalData": "Student Data",
    "sensitivePersonalData": False,
    "additionalInformation": "N/A",
    "declarationName": "EduCare Foundation",
    "declarationDesignation": "Chairperson",
    "declarationDate": "2024-04-01"
  },
  {
    "id": 5,
    "entityName": "Green Energy Solutions",
    "registrationNumber": "321987",
    "licenseNumber": "LIC321987",
    "lawNumber": "LAW321",
    "presidentialOrderNumber": "PO321",
    "natureOfEntity": "Private",
    "entitySector": "Energy",
    "entityAddress": "Kigali",
    "phoneNumber": "Green Energy Solutions",
    "emailAddress": "greenenergy@gmail.com",
    "website": "www.greenenergy.com",
    "dpoName": "Sarah Adams",
    "dpoPhoneNumber": "0785789012",
    "dpoEmailAddress": "sarahadams@gmail.com",
    "representativeName": "David Clark",
    "representativePhoneNumber": "0785890123",
    "representativeAddress": "321 Green Lane",
    "representativeEmail": "davidclark@gmail.com",
    "representativeWebsite": "www.davidclark.com",
    "categoryOfDataSubjects": "Customers",
    "purposeOfDataProcessing": "Energy Usage Data",
    "transferOfPersonalDataOutsideRwanda": True,
    "transferCountry": "Uganda",
    "categoriesOfPersonalData": "Energy Data",
    "sensitivePersonalData": False,
    "additionalInformation": "Green Initiative",
    "declarationName": "Green Energy Solutions",
    "declarationDesignation": "COO",
    "declarationDate": "2024-04-15"
  },
  {
    "id": 6,
    "entityName": "Finance First",
    "registrationNumber": "456789",
    "licenseNumber": "LIC456789",
    "lawNumber": "LAW456",
    "presidentialOrderNumber": "PO456",
    "natureOfEntity": "Private",
    "entitySector": "Finance",
    "entityAddress": "Kigali",
    "phoneNumber": "Finance First",
    "emailAddress": "financefirst@gmail.com",
    "website": "www.financefirst.com",
    "dpoName": "Linda Brown",
    "dpoPhoneNumber": "0785901234",
    "dpoEmailAddress": "lindabrown@gmail.com",
    "representativeName": "Robert Johnson",
    "representativePhoneNumber": "0786012345",
    "representativeAddress": "456 Finance Street",
    "representativeEmail": "robertjohnson@gmail.com",
    "representativeWebsite": "www.robertjohnson.com",
    "categoryOfDataSubjects": "Clients",
    "purposeOfDataProcessing": "Financial Data",
    "transferOfPersonalDataOutsideRwanda": False,
    "transferCountry": None,
    "categoriesOfPersonalData": "Financial Data",
    "sensitivePersonalData": True,
    "additionalInformation": "Private Banking",
    "declarationName": "Finance First",
    "declarationDesignation": "CIO",
    "declarationDate": "2024-05-01"
  },
  {
    "id": 7,
    "entityName": "Agriculture Advances",
    "registrationNumber": "987654",
    "licenseNumber": "LIC987654",
    "lawNumber": "LAW987",
    "presidentialOrderNumber": "PO987",
    "natureOfEntity": "Public",
    "entitySector": "Agriculture",
    "entityAddress": "Kigali",
    "phoneNumber": "Agriculture Advances",
    "emailAddress": "agricultureadvances@gmail.com",
    "website": "www.agricultureadvances.com",
    "dpoName": "James Wilson",
    "dpoPhoneNumber": "0786123456",
    "dpoEmailAddress": "jameswilson@gmail.com",
    "representativeName": "Emma Davis",
    "representativePhoneNumber": "0786234567",
    "representativeAddress": "789 Agriculture Road",
    "representativeEmail": "emmadavis@gmail.com",
    "representativeWebsite": "www.emmadavis.com",
    "categoryOfDataSubjects": "Farmers",
    "purposeOfDataProcessing": "Crop Data",
    "transferOfPersonalDataOutsideRwanda": True,
    "transferCountry": "Tanzania",
    "categoriesOfPersonalData": "Agricultural Data",
    "sensitivePersonalData": False,
    "additionalInformation": "N/A",
    "declarationName": "Agriculture Advances",
    "declarationDesignation": "Director",
    "declarationDate": "2024-05-15"
  }
]


for entity in entityData:
    DataProcessor.objects.create(
        entity_name=entity["entityName"],
        registration_number=entity["registrationNumber"],
        license_number=entity["licenseNumber"],
        law_number=entity["lawNumber"],
        presidential_order_number=entity["presidentialOrderNumber"],
        nature_of_entity=entity["natureOfEntity"],
        entity_sector=entity["entitySector"],
        entity_address=entity["entityAddress"],
        phone_number=entity["phoneNumber"],
        email_address=entity["emailAddress"],
        website=entity["website"],
        dpo_name=entity["dpoName"],
        dpo_phone_number=entity["dpoPhoneNumber"],
        dpo_email_address=entity["dpoEmailAddress"],
        representative_name=entity["representativeName"],
        representative_phone_number=entity["representativePhoneNumber"],
        representative_address=entity["representativeAddress"],
        representative_email=entity["representativeEmail"],
        representative_website=entity["representativeWebsite"],
        category_of_data_subjects=entity["categoryOfDataSubjects"],
        purpose_of_data_processing=entity["purposeOfDataProcessing"],
        transfer_of_personal_data_outside_rwanda=entity["transferOfPersonalDataOutsideRwanda"],
        transfer_country=entity["transferCountry"],
        categories_of_personal_data=entity["categoriesOfPersonalData"],
        sensitive_personal_data=entity["sensitivePersonalData"],
        additional_information=entity["additionalInformation"],
        declaration_name=entity["declarationName"],
        declaration_designation=entity["declarationDesignation"],
        declaration_date=datetime.strptime(entity["declarationDate"], "%Y-%m-%d").date(),
        is_approved=0  # or some logic to determine this value
    )
