# Generated by Django 5.0.6 on 2024-06-02 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataController',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_name', models.CharField(max_length=255)),
                ('registration_number', models.CharField(blank=True, max_length=255, null=True)),
                ('license_number', models.CharField(blank=True, max_length=255, null=True)),
                ('law_number', models.CharField(blank=True, max_length=255, null=True)),
                ('presidential_order_number', models.CharField(blank=True, max_length=255, null=True)),
                ('nature_of_entity', models.CharField(choices=[('Public', 'Public'), ('Private', 'Private'), ('NGO', 'NGO'), ('Faith Based Organization', 'Faith Based Organization'), ('Political Organization', 'Political Organization'), ('Development Partner', 'Development Partner'), ('Other', 'Other')], max_length=50)),
                ('entity_sector', models.CharField(max_length=255)),
                ('entity_address', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=50)),
                ('email_address', models.EmailField(max_length=254)),
                ('website', models.URLField(blank=True, null=True)),
                ('dpo_name', models.CharField(max_length=255)),
                ('dpo_phone_number', models.CharField(max_length=50)),
                ('dpo_email_address', models.EmailField(max_length=254)),
                ('representative_name', models.CharField(blank=True, max_length=255, null=True)),
                ('representative_phone_number', models.CharField(blank=True, max_length=50, null=True)),
                ('representative_address', models.CharField(blank=True, max_length=255, null=True)),
                ('representative_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('representative_website', models.URLField(blank=True, null=True)),
                ('category_of_data_subjects', models.CharField(max_length=255)),
                ('purpose_of_data_processing', models.CharField(max_length=255)),
                ('transfer_of_personal_data_outside_rwanda', models.BooleanField()),
                ('transfer_country', models.CharField(blank=True, max_length=255, null=True)),
                ('categories_of_personal_data', models.CharField(max_length=255)),
                ('sensitive_personal_data', models.BooleanField()),
                ('additional_information', models.TextField(blank=True, null=True)),
                ('declaration_name', models.CharField(max_length=255)),
                ('declaration_designation', models.CharField(max_length=255)),
                ('declaration_date', models.DateField()),
            ],
        ),
    ]
